name: CustomCrafting
authors: [ WolfyScript ]
main: com.wolfyscript.customcrafting.spigot.CustomCraftingSpigotBootstrap
version: ${version}
api-version: "1.21.5"
depend: [ scafall, NBTAPI ]
loadbefore:
  - DiSky
  - EpicWorldGenerator
softdepend: [ ProtocolLib, MythicMobs, Oraxen, ItemsAdder, PlaceholderAPI, EcoEnchants, EcoItems, EcoArmor, EcoSkills, EcoBosses ]
description: Create your own custom recipes for workbenches and furnaces. Disable Vanilla recipes and more.

