/*
 *       ____ _  _ ____ ___ ____ _  _ ____ ____ ____ ____ ___ _ _  _ ____
 *       |    |  | [__   |  |  | |\/| |    |__/ |__| |___  |  | |\ | | __
 *       |___ |__| ___]  |  |__| |  | |___ |  \ |  | |     |  | | \| |__]
 *
 *       CustomCrafting Recipe creation and management tool for Minecraft
 *                      Copyright (C) 2021  WolfyScript
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "customcrafting"

pluginManagement {
    repositories {
        mavenLocal()
        mavenCentral()
        gradlePluginPortal()
        maven {
            name = "Fabric"
            url = uri("https://maven.fabricmc.net")
            content {
                includeGroupAndSubgroups("net.fabricmc")
                includeGroup("fabric-loom")
            }
        }
        maven {
            name = "Sponge"
            url = uri("https://repo.spongepowered.org/repository/maven-public")
            content {
                includeGroupAndSubgroups("org.spongepowered")
            }
        }
        maven {
            name = "Forge"
            url = uri("https://maven.minecraftforge.net")
            content {
                includeGroupAndSubgroups("net.minecraftforge")
            }
        }
        maven("https://artifacts.wolfyscript.com/artifactory/gradle-dev")
    }
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
}

/**
 * # Core
 * This contains the core functionality of CustomCrafting.
 * Which includes
 * - all the features for custom recipes
 * - registration of custom recipes and components
 * - de-/serialization of all the content
 * - database and file management
 *
 * The core is the only module required to get CustomCrafting to run.
 * Recipe files can be modified with any text-editor that support the HOCON format.
 *
 * The Editor and UI modules are optional and provide a way to edit content in-game.
 */
sequenceOf(
    "api",
    "common",
    "spigotlike",
    "spigot",
    "paper",
    "fabric",
).forEach {
    include(":core:${it}")
    project(":core:${it}").projectDir = file("core/${it.replace(":", "/")}")
}

/**
 * # Editor
 * The editor module contains all the functionality for the editor.
 * That includes,
 * - the data models, that reflect objects in the editor,
 * - use-cases, that contain the logic to modify the models,
 * - the repository that stores the data,
 * - and the CLI that allows editing recipes via commands.
 */
sequenceOf(
    "api",
).forEach {
    include(":editor:${it}")
    project(":editor:${it}").projectDir = file("editor/${it.replace(":", "/")}")
}

/**
 * # UI
 * > Requires the Editor module.
 * Adds a UI that allows editing and creating content with an in-game UI.
 */
sequenceOf(
    "api",
).forEach {
    include(":ui:${it}")
    project(":ui:${it}").projectDir = file("ui/${it.replace(":", "/")}")
}
