type = crafting
priority = 200 # takes precedence over the default/golder_apple_random_crafting recipe by increasing the priority.
               # alternatively the priority of the other recipe can be decreased, or both as done here.

formula {
  type = "shaped"

  mappedIngredients {
    G: {
      choices {
        stacks = [
          {
            identifier {
              type = vanilla
              stack {
                version = 4325 // The data version at time it was saved. Used to updgrade using DataFixerUpper. Can be ommitted to use current version, bypassing upgrades.
                snbt = "{id:'gold_block'}"
              }
            }
          }
        ]
      }
      consumption {
        type = replace
        replacement {
          identifier {
            type = vanilla
            stack = "{id:'apple'}"
          }
        }
      }
      matching {
        type = item
      }
    }
    A: {
      choices {
        stacks = [
          {
            identifier {
              type = vanilla
              stack = "{id:'apple'}"
            }
          }
        ]
      }

      matching {
        type = item
        // Item must be of the same type and must have a custom item name component
        mustContain = [
          "minecraft:item_name"
        ]
      }

      consumption {
        type = keep
      }
    }
  }

  shape {
    rows = [
      "GGG",
      "GAG",
      "GGG"
    ],
    symmetry {
      horizontal = false
      vertical = false
      rotate = false
    }
    trim = false
  }
}

result {
  modifier {}
  choices {
    stacks = [
      {
        identifier {
          type = vanilla
          stack = "{id:'enchanted_golden_apple'}"
        }
      }
    ]
  }
  actions = [
    {
      type = command
      // Commands are parsed using the complete execution context
      // If executed on a position (crafting table, furnace, etc.) or executed by a player (crafting table, player inv, virtual furnace inv, etc.) it is taken into account
      // So the @ selector acts properly like one would expect, and more advanced selectors like ranges, etc. will also work.
      commands = [
        "effect give @s minecraft:weakness 20 2 false"
        "effect give @s minecraft:blindness 20 2 false"
      ]
    }
  ]
  bulkActions = []
}