type = crafting

formula {
  type = "shaped"

  mappedIngredients {
    G: {
      choices {
        stacks = [
          {
            identifier {
              type = vanilla
              stack = "{id:'pufferfish'}"
            }
          }
        ]
      }
    }
    A: {
      choices {
        stacks = [
          {
            identifier {
              type = vanilla
              stack = "{id:'water_bucket'}"
            }
          }
        ]
      }

      consumption {
        type = consume
        remains {
          type = default
          ignore {
            vanilla = true
            others = true
          }
        }
      }
    }
  }

  shape {
    rows = [
      "G",
      "A"
    ],
    symmetry {
      horizontal = false
      vertical = false
      rotate = false
    }
  }
}

result {
  modifier {}
  choices {
    stacks = [
      {
        identifier {
          type = vanilla
          stack = "{id:'pufferfish_bucket'}"
        }
      }
    ]
  }
  bulkActions = []
}
