type = cooking

result {
  modifier {}
  choices {
    stacks = [
      {
        identifier {
          type = vanilla
          stack = "{id:'iron_block'}"
        }
      },
      {
        identifier {
          type = vanilla
          stack = "{id:'iron_block'}"
        }
      },
      {
        amount = 2
        identifier {
          type = vanilla
          stack = "{id:'iron_block'}"
        }
      },
      {
        amount = 3
        identifier {
          type = vanilla
          stack = "{id:'iron_block'}"
        }
      }
    ]
  }
}

processing {
  type = blasting
  processingTime = 100
  source  {
    choices {
      stacks = [
        {
          identifier {
            type = vanilla
            stack = "{id:'raw_iron_block'}"
          }
        }
      ]
    }
  }
}