type = cooking

result {
  modifier {}
  choices {
    stacks = [
      {
        identifier {
          type = vanilla
          stack = "{id:'charcoal'}"
        }
      }
    ]
  }
}

processing {
  type = campfire
  processingTime = 60
  soulCampfire = true
  normalCampfire = true
  source  {
    choices {
      stacks = [
        {
          identifier {
            type = vanilla
            stack = "{id:'cooked_beef'}"
          }
        }
      ]
    }

    consumption {
      type = replace
      replacement {
        identifier {
          type = vanilla
          stack = "{id:'beef'}"
        }
      }
    }
  }
}
