destinations = [
  {
    type = local
    path = default
    filter {
      includes {
        // do not include anything and prevent any recipe to be saved to the defaults
      }
    }
    overwriteExisting = false
  },
  {
    // Custom Recipes created via gui/cli
    type = local
    path = custom
    filter {
      // Namespaces specify the plugin/mod the recipes are coming from to prevent name clashes.
      // All the recipes you may create in-game are therefor provided by CustomCrafting and are in the 'customcrafting' namespace.
      // When saving a recipe you can choose a directory though that you can also filter.
      includes {
        namespaces = [ customcrafting ]
      }
    }
    overwriteExisting = true // you can override default recipes
  },
  // Load and save recipes from/to an SQL server
//  {
//    type = sql
//    host = ""
//    schema = ""
//    username = ""
//    password = ""
//  },
  {
    type = local
    path = backup
    filter {
      includes {
        namespaces = [ customcrafting ]
      }
    }
    backup {
      // Marks this destination as a backup destination
      // No recipes will be loaded from this one. Only saved!
      // TODO: No backup options yet
    }
  }
]