type = crafting

formula {
  type = shaped

  mappedIngredients {
    G: {
      choices {
        stacks = [
          {
            identifier {
              type = vanilla
              stack = "{id:'stick'}"
            }
          }
        ]
      }
    }
    A: {
      choices {
        stacks = [
          {
            identifier {
              type = vanilla
              stack = "{id:'nether_star'}"
            }
          }
        ]
      }
    }
    B: {
      choices {
        stacks = [
          {
            identifier {
              type = vanilla
              stack = "{id:'netherite_ingot'}"
            }
          }
        ]
      }
    }
  }

  shape {
    rows = [
      "  A",
      " B ",
      "G  "
    ],
    symmetry {
      horizontal = true
      vertical = true
      rotate = true
    }
  }
}

result {
  modifier {}
  choices {
    stacks = [
      {
        identifier {
          type = vanilla
          stack = "{id:'debug_stick'}"
        }
      }
    ]
  }
  bulkActions = []
}
