type = grinding
priority = 0
conditions {
  conditions = []
}

base {
  choices {
    stacks = [
      {
        amount = 1
        identifier {
          type = vanilla
          stack = "{id:'netherite_sword'}"
        }
      }
    ]
  }
}

process {
  type = "default"



}
