type = grinding

base {
  choices {
    stacks = [
      {
        identifier {
          type = vanilla
          stack = "{id:'netherite_chestplate'}"
        }
      }
    ]
  }
  matching {
    type = item
  }
}

addition {
  choices {
    stacks = [
      {
        identifier {
          type = vanilla
          stack = "{id:'ghast_tear'}"
        }
      }
    ]
  }
  matching {
    type = item
  }
}

process {
  type = "default"
  mergeEnchants {
    upgradeEnchants = true
  }
  removeEnchants {
    baseEnchants {
      removeCurses = true
      type = REMOVE
    }
    additionEnchants {
      type = REMOVE
      removeCurses = true
    }
  }
}
