type = grinding

base {
  choices {
    stacks = [
      {
        identifier {
          type = vanilla
          stack = "{id:'netherite_sword'}"
        }
      }
    ]
  }
  matching {
    type = item
  }
}

process {
  type = "default"

  removeEnchants {
    baseEnchants {
      removeCurses = true
      enchants = [
        "minecraft:fire_aspect"
      ]
      type = REMOVE
    }
  }

}
