type = grinding

base {
  choices {
    stacks = [
      {
        identifier {
          type = vanilla
          stack = "{id:'netherite_sword'}"
        }
      }
    ]
  }
}

process {
  type = "default"



}
