type = crafting

formula {
  type = "shaped"

  mappedIngredients {
    G: {
      choices {
        stacks = [
          {
            identifier {
              type = vanilla
              stack = "{id:'gold_block'}"
            }
          }
        ]
      }
    }
    A: {
      choices {
        stacks = [
          {
            identifier {
              type = vanilla
              stack = "{id:'apple'}"
            }
          }
        ]
      }
    }
  }

  shape {
    rows = [
      "GGG",
      "GAG",
      "GGG"
    ],
    symmetry {
      horizontal = false
      vertical = false
      rotate = false
    }
    trim = false
  }
}

result {
  alwaysKeepPrevious = true
  modifier {}
  choices {
    stacks = [
      {
        identifier {
          type = vanilla
          stack = "{id:'golden_apple'}"
        }
      },
      {
        identifier {
          type = vanilla
          stack = "{id:'golden_apple'}"
        }
      },
      {
        identifier {
          type = vanilla
          stack = "{id:'golden_apple'}"
        }
      },
      {
        identifier {
          type = vanilla
          stack = "{id:'golden_apple'}"
        }
      },
      {
        identifier {
          type = vanilla
          stack = "{id:'golden_apple'}"
        }
      },
      {
        identifier {
          type = vanilla
          stack = "{id:'golden_apple'}"
        }
      },
      {
        identifier {
          type = vanilla
          stack = "{id:'golden_apple'}"
        }
      },
      {
        identifier {
          type = vanilla
          stack = "{id:'enchanted_golden_apple'}"
        }
      },
    ]
  }
  bulkActions = []
}
