type = stonecutting
priority = 0
conditions {
  conditions = []
}

source  {
  choices {
    stacks = [
      {
        amount = 1
        identifier {
          type = vanilla
          stack {
            version = 4325
            snbt = "{id:'oak_leaves'}"
          }
        }
      }
    ]
  }
  replaceWithRemains = false
}

flattenResult = true
result {
  modifier {}
  choices {
    stacks = [
      {
        amount = 1
        identifier {
          type = vanilla
          stack = "{id:'spruce_leaves'}"
        }
      }, {
        amount = 1
        identifier {
          type = vanilla
          stack = "{id:'birch_leaves'}"
        }
      }, {
        amount = 1
        identifier {
          type = vanilla
          stack = "{id:'jungle_leaves'}"
        }
      }, {
        amount = 1
        identifier {
          type = vanilla
          stack = "{id:'acacia_leaves'}"
        }
      }, {
        amount = 1
        identifier {
          type = vanilla
          stack = "{id:'dark_oak_leaves'}"
        }
      }, {
        amount = 1
        identifier {
          type = vanilla
          stack = "{id:'mangrove_leaves'}"
        }
      }
    ]
  }
  actions = [
    {
      type = command
      // Commands are parsed using the complete execution context
      // If executed on a position (crafting table, furnace, etc.) or executed by a player (crafting table, player inv, virtual furnace inv, etc.) it is taken into account
      // So the @ selector acts properly like one would expect, and more advanced selectors like ranges, etc. will also work.
      commands = [
        "effect give @e[distance=..4] minecraft:absorption 20 4 false"
      ]
    }
  ]
  bulkActions = []
}
