type = repairing
priority = 0
conditions {
  conditions = []
}

base {
  choices {
    stacks = [
      {
        amount = 1
        identifier {
          type = vanilla
          stack = "{id:'netherite_sword'}"
        }
      }
    ]
  }
}

addition {
  choices {
    stacks = [
      {
        amount = 1
        identifier {
          type = vanilla
          stack = "{id:'amethyst_shard'}"
        }
      }
    ]
  }
}

process {
  type = "custom"
  rename {
    formatted = true
    cost = 40 // yes, levels above the vanilla limit of 40 is possible. The vanilla limit is ignored!
              // One downside though, "Too Expensive" is still displayed, but the result can be collected anyways.
  }
  itemRepair {
    cost = 4
    combineEnchants = true
  }

}
