type = cooking

result {
  modifier {}
  choices {
    stacks = [
      {
        identifier {
          type = vanilla
          stack = "{id:'leather'}"
        }
      }
    ]
  }
  actions = [
    {
      type = command
      // Commands are parsed using the complete execution context
      // If executed on a position (crafting table, furnace, etc.) or executed by a player (crafting table, player inv, virtual furnace inv, etc.) it is taken into account
      // So the @ selector acts properly like one would expect, and more advanced selectors like ranges, etc. will also work.
      commands = [
        "effect give @p[distance=..4] minecraft:nausea 20 2"
      ]
    }
  ]
}

processing {
  type = smelting
  processingTime = 100
  source  {
    choices {
      stacks = [
        {
          identifier {
            type = vanilla
            stack {
              version = 4325
              snbt = "{id:'rotten_flesh'}"
            }
          }
        }
      ]
    }
  }
}
