type = cooking

result {
  modifier {}
  choices {
    stacks = [
      {
        identifier {
          type = vanilla
          stack = "{id:'leather'}"
        }
      }
    ]
  }
  actions = [
    {
      type = command
      commands = [
        "effect give @p[distance=..4] minecraft:poison 10 2"
        "effect give @p[distance=..6] minecraft:nausea 40 2"
      ]
    }
  ]
}

processing {
  type = smoking
  processingTime = 40
  source  {
    choices {
      stacks = [
        {
          identifier {
            type = vanilla
            stack {
              version = 4325
              snbt = "{id:'rotten_flesh'}"
            }
          }
        }
      ]
    }
  }

}
