type = cooking

result {
  modifier {}
  choices {
    stacks = [
      {
        amount = 1
        identifier {
          type = vanilla
          stack = "{id:'torch'}"
        }
      }
    ]
  }
  actions = [
    {
      type = command
      commands = [
        "particle minecraft:flame ~ ~ ~ 0 0 0 0.04 200"
      ]
    }
  ]
}

processing {
  type = campfire
  processingTime = 60
  soulCampfire = false
  source  {
    choices {
      stacks = [
        {
          amount = 1
          identifier {
            type = vanilla
            stack {
              version = 4325
              snbt = "{id:'stick'}"
            }
          }
        }
      ]
    }
  }

}
