type = cooking
priority = 0
conditions {
  conditions = []
}

result {
  modifier {}
  choices {
    stacks = [
      {
        amount = 1
        identifier {
          type = vanilla
          stack = "{id:'soul_torch'}"
        }
      }
    ]
  }
  actions = [
    {
      type = command
      commands = [
        "particle minecraft:soul_fire_flame ~ ~ ~ 0 0 0 0.04 200"
      ]
    }
  ]
}

processing {
  type = campfire
  processingTime = 60
  soulCampfire = true
  normalCampfire = false
  source  {
    choices {
      stacks = [
        {
          amount = 1
          identifier {
            type = vanilla
            stack {
              version = 4325
              snbt = "{id:'stick',count:1}"
            }
          }
        }
      ]
    }
    replaceWithRemains = false
  }

}
