type = crafting

formula {
  type = "shapeless"
  ingredients = [
    {
      choices {
        stacks = [
          {
            identifier {
              type = vanilla
              stack = "{id:'enchanted_golden_apple'}"
            }
          }
        ]
      }
    }, {
      choices {
        stacks = [
          {
            identifier {
              type = vanilla
              stack = "{id:'golden_apple'}"
            }
          }
        ]
      }
    }, {
      choices {
        stacks = [
          {
            identifier {
              type = vanilla
              stack = "{id:'golden_carrot'}"
            }
          }
        ]
      }
    }, {
      choices {
        stacks = [
          {
            identifier {
              type = vanilla
              stack = "{id:'bowl'}"
            }
          }
        ]
      }
    }
  ]
}

result {
  modifier {}
  choices {
    stacks = [
      {
        identifier {
          type = vanilla
          stack = "{id:'suspicious_stew',components:{'minecraft:suspicious_stew_effects':[{id:'regeneration',duration:600},{id:'absorption',duration:4800},{id:'fire_resistance',duration:8000},{id:'resistance',duration:8000}]}}"
        }
      }
    ]
  }
  actions = [
    {
      type = command
      // Commands are parsed using the complete execution context
      // If executed on a position (crafting table, furnace, etc.) or executed by a player (crafting table, player inv, virtual furnace inv, etc.) it is taken into account
      // So the @ selector acts properly like one would expect, and more advanced selectors like ranges, etc. will also work.
      commands = [
        "effect give @e[distance=..4] minecraft:absorption 20 4 false"
      ]
    }
  ]
  bulkActions = []
}