type = smithing
priority = 0
conditions {}

template = null // some recipes do not require ingredients for each slot.
                // A left out ingredient means the slot needs to be emtpy!

base {
  choices {
    stacks = [
      {
        amount = 1
        identifier {
          type = vanilla
          stack = "{id:'netherite_sword',count:1}"
        }
      }
    ]
  }
  matchTags = false
}

addition {
  choices {
    stacks = [
      {
        amount = 1
        identifier {
          type = vanilla
          stack = "{id:'nether_star',count:1}"
        }
      }
    ]
  }
}

copyOptions {
  // Copy options can be used to compose copy, replace or remove operations
  // Exclude together with pre-defined components on result, would basically be a replace operation,
  // Include a copy, and exclude without pre-defined components a remove operation.
  // For more control about what parts of a component is copied, or merging of the same components, result transformations are required.
  excludeComponents = [
    "minecraft:attribute_modifiers"
    "minecraft:max_damage"
  ]
}

result {
  modifier {}
  choices {
    stacks = [
      {
        amount = 1
        identifier {
          type = vanilla
          stack = "{id:'netherite_sword',count:1,components:{attribute_modifiers:[{type:'attack_damage',operation:'add_value',amount:11.0d,id:'minecraft:base_attack_damage',slot:'hand'},{type:'attack_speed',operation:'add_value',amount:2.0d,id:'minecraft:base_attack_speed',slot:'hand'}]}}"
        }
      }
    ]
  }
}
