type = smithing

template = null // some recipes do not require ingredients for each slot.
                // A left out ingredient means the slot needs to be emtpy!

base {
  choices {
    stacks = [
      {
        identifier {
          type = vanilla
          stack = "{id:'netherite_sword'}"
        }
      }
    ]
  }
}

addition {
  choices {
    stacks = [
      {
        identifier {
          type = vanilla
          stack = "{id:'nether_star'}"
        }
      }
    ]
  }
}

copyOptions {
  // Copy options can be used to compose operations like copy, replace or remove
  // * Replace: Exclude components together with pre-defined components on result
  // * Copy: Include components to copy specific components
  // * Remove: Exclude components without pre-defined components on result
  //
  // For more control about what parts of a component is copied, or merging of the same components, result modifiers are required.
  excludeComponents = [
    "minecraft:attribute_modifiers"
    "minecraft:max_damage"
  ]
}

result {
  modifier {}
  choices {
    stacks = [
      {
        identifier {
          type = vanilla
          stack = "{id:'netherite_sword',components:{attribute_modifiers:[{type:'attack_damage',operation:'add_value',amount:11.0d,id:'minecraft:base_attack_damage',slot:'hand'},{type:'attack_speed',operation:'add_value',amount:2.0d,id:'minecraft:base_attack_speed',slot:'hand'}]}}"
        }
      }
    ]
  }
}
