# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
# Kotlin & Jetbrains
kotlin = "2.2.0"
jetbrains-annotations = "23.0.0"
exposed = "1.0.0-beta-2"

# Configuration
jackson = "2.19.0"
dataformat-hocon = "2.1-SNAPSHOT"
typesafe-config = "1.3.1"
jackson-kotlin = "2.13.4"

# database drivers
h2 = "2.2.224"
mariadb = "3.3.1"
mysql = "8.0.33"
oracledb = "12.2.0.1"
postgresql = "42.7.7"
ms-sqlserver = "9.4.1.jre8"
sqlite = "3.50.1.0"

# error tracking
sentry = "8.22.0"

# cross-platform APIs
scafall = "alpha0.4.0.0-SNAPSHOT"
adventure-api = "4.10.1"
adventure-platform-api = "4.1.0"
adventure-minimessage = "4.10.0"

# Minecraft
minecraft = "1.21.8"
authlib = "6.0.58"
fastutil = "8.5.15"
netty = "4.1.74.Final"

# Utils, Dependency Injection & Misc
guice = "7.0.0"
junit-jupiter = "5.8.2"
caffeine = "3.2.0"
slf4j-api = "2.0.16"

# Spigot/Paper/Folia
wolfyutils = "4.19-SNAPSHOT"
papermc = "1.21.8-R0.1-SNAPSHOT"
bstats-bukkit = "3.0.0"
item-nbt-api = "2.11.3"
mythic = "5.3.5"
placeholderapi = "2.11.6"
oraxen = "1.170.0"
protocollib = "5.3.0"
bstats = "3.0.0"

# modded
parchment = "2025.07.20"

# Sponge
sponge-gradle = "2.2.0"
sponge-api = "15.0.0-SNAPSHOT"

## Fabric Impl
fabric-api = "0.131.0+1.21.8"
fabric-loader = "0.17.1"
fabric-kotlin="1.13.4+kotlin.2.2.0"

# Forge
forge = "55.0.1"
forge-loader-range = "[55,)"

# NeoForge
neoforge_version = "21.5.4-beta"
neoforge_loader_version_range = "[4,)"

# Gradle plugins
fabric-loom = "1.11-SNAPSHOT"
shadow = "9.0.1"
dev-tools = "a2.2.0.0"
artifactory = "5+"
paperweight-userdev = "2.0.0-beta.18"
minotaur = "2.+"
resource-factory = "1.3.0"

[libraries]
# Kotlin & Jetbrains
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
exposed-json = { module = "org.jetbrains.exposed:exposed-json", version.ref = "exposed" }

# Configurations
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson" }
jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson" }
jackson-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson-kotlin" }
jackson-dataformat-hocon = { module = "com.wolfyscript:jackson-dataformat-hocon", version.ref = "dataformat-hocon" }
typesafe-config = { module = "com.typesafe:config", version.ref = "typesafe-config" }

# database drivers
db-h2 = { module = "com.h2database:h2", version.ref = "h2" }
db-mariadb = { module = "org.mariadb.jdbc:mariadb-java-client", version.ref = "mariadb" }
db-mysql = { module = "mysql:mysql-connector-java", version.ref = "mysql" }
db-oracle = { module = "com.oracle.database.jdbc:ojdbc8", version.ref = "oracledb" }
db-postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
db-sqlserver = { module = "com.microsoft.sqlserver:mssql-jdbc", version.ref = "ms-sqlserver" }
db-sqlite = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite" }

# cross-platform APIs
scafall-api = { module = "com.wolfyscript.scafall:api", version.ref = "scafall" }
scafall-loader = { module = "com.wolfyscript.scafall.loader:loader-api", version.ref = "scafall" }
scafall-sponge-impl = { module = "com.wolfyscript.scafall.sponge:sponge", version.ref = "scafall" }
## Adventure
adventure-api = { module = "net.kyori:adventure-api", version.ref = "adventure-api" }
adventure-platform-api = { module = "net.kyori:adventure-platform-api", version.ref = "adventure-platform-api" }
adventure-minimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure-minimessage" }

# Minecraft
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
mojang-authlib = { module = "com.mojang:authlib", version.ref = "authlib" }
fastutil = { module = "it.unimi.dsi:fastutil", version.ref = "fastutil" }
netty-all = { module = "io.netty:netty-all", version.ref = "netty" }

# Utils & Misc
inject-guice = { module = "com.google.inject:guice", version.ref = "guice" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine"}
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j-api" }
sentry-log4j2 = { module = "io.sentry:sentry-log4j2", version.ref = "sentry" }
sentry = { module = "io.sentry:sentry", version.ref = "sentry" }

# Testing
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }

# Spigot/Paper/Folia
scafall-spigot-api = { module = "com.wolfyscript.scafall.spigot:spigot-api", version.ref = "scafall" }
wolfyutils-spigot = { module = "com.wolfyscript.wolfyutils.spigot:wolfyutils-spigot", version.ref = "wolfyutils" }
papermc-paper = { module = "io.papermc.paper:paper-api", version.ref = "papermc" }
adventure-platform-bukkit = { module = "net.kyori:adventure-platform-bukkit", version.ref = "adventure-platform-api" }
bstats = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }
nbtapi = { module = "de.tr7zw:item-nbt-api-plugin", version.ref = "item-nbt-api"}
mythic-dist = { module = "io.lumine:Mythic-Dist", version.ref = "mythic" }
placeholderapi = { module = "me.clip:placeholderapi", version.ref = "placeholderapi" }
oraxen = { module = "io.th0rgal:oraxen", version.ref = "oraxen"}
protocollib = { module = "com.comphenix.protocol:ProtocolLib", version.ref = "protocollib" }

# Sponge
spongepowered-api = { module = "org.spongepowered:spongeapi", version.ref = "sponge-api" }

## Fabric
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-kotlin" }

[bundles]
jetbrains = [ "kotlin-stdlib", "jetbrains-annotations" ]
exposed = [ "exposed-core", "exposed-jdbc", "exposed-json" ]
database-drivers = [ "db-h2", "db-mariadb", "db-mysql", "db-oracle", "db-postgresql", "db-sqlite", "db-sqlserver" ]
adventure = [ "adventure-api", "adventure-minimessage", "adventure-platform-api" ]
jackson = [ "jackson-databind", "jackson-dataformat-hocon" ]
minecraft-deps = [ "mojang-authlib", "fastutil", "netty-all" ]
testing = [ "junit-jupiter" ]
sentry = [ "sentry", "sentry-log4j2"]

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
spongepowered-gradle = { id = "org.spongepowered.gradle.plugin", version.ref = "sponge-gradle" }
devtools-docker-run = { id = "com.wolfyscript.devtools.docker.run", version.ref = "dev-tools" }
devtools-docker-minecraft = { id = "com.wolfyscript.devtools.docker.minecraft_servers", version.ref = "dev-tools" }
artifactory = { id = "com.jfrog.artifactory", version.ref = "artifactory"}
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
paperweight-userdev = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight-userdev" }
modrinth-minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }
resource-factory-bukkit = { id = "xyz.jpenilla.resource-factory-bukkit-convention", version.ref= "resource-factory"}
