sources = [
  {
    type = directory
    path = default
    filter {
      includes {
        // do not include anything and prevent any recipe to be saved to the defaults
      }
    }
    overwriteExisting = false
  },
  {
    // Custom Recipes created via gui/cli
    type = directory
    path = custom
    filter {
      // Namespaces specify the plugin/mod the recipes are coming from to prevent name clashes.
      // All the recipes you may create in-game are therefor provided by CustomCrafting and are in the 'customcrafting' namespace.
      // When saving a recipe you can choose a directory though that you can also filter.
      includes {
        namespaces = [ customcrafting ]
      }
    }
    overwriteExisting = true // resources loaded from this destination override existing resources with the same path
  },
  // Load and save recipes from/to an SQL server
//  {
//    type = sql
//    host = ""
//    schema = ""
//    username = ""
//    password = ""
//  },
]

backup {
  destinations = [
    {
      type = directory
      path = backup
      keep = 8 // Keep the past 8 backups
      compress = true // compress into a zip file. uncompressed directories are also possible
    }
  ]
}