package com.wolfyscript.customcrafting.editor.domain.model.recipe

import com.wolfyscript.customcrafting.core.recipes.CustomRecipeStonecutting

interface RecipeStonecuttingModel : RecipeModel.RecipeTypeSpecificModel<CustomRecipeStonecutting>